
#server port
server:
  port: 8300



#application name
spring:
  application:
    name: order-service

#product-service:
 # ribbon:
  #  eureka:
   #   enabled: false
    #listOfServers: localhost:8001,localhost:8002
    #ServerListRefreshInterval: 15000
    
# Eureka server url
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/cloud-Discovery/eureka
